databases:
  - name: venulet_production
    ipAllowList: []
    databaseName: venulet_production
    user: venulet_production_user
    region: frankfurt

services:
  - type: web
    name: venulet_rails
    env: ruby
    repo: https://github.com/fordburgess/event-hosting
    branch: master
    rootDir: .
    healthCheckPath: /
    buildCommand: "./bin/render-build.sh"
    startCommand: |
      "bundle exec puma -C config/puma.rb"
      "RAILS_ENV=production bundle exec rails db:migrate && RAILS_ENV=production bundle exec rails db:seed"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: venulet_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
    region: frankfurt
